### ISSUE TITLE
Compilation Time/Code Size Regression with GHC 8.0.1 

### ISSUE THREAD

**Issue by kandersen** [wrengr/unification-fd#2] opened 2017-01-06 13:41 UTC
The GHC inliner on the current LTS Stackage release doesn't like the Eq and Ord instances on Fix.

The following code, compiled with GHC 8.0.1 with `-v` blows from ~50 "terms" to 500,000 "terms".

Putting a `{-# NOINLINE (==) #-}` pragma on the instance for `Eq (Fix f)`, or writing a manual instance for `Eq (Foo' a)` with a similar pragma solves my issue. For now I am doing the second as a work around.

The issue can be tested with LTS-7.2 through to LTS-7.14, and is not present on LTS-6.27.

````
newtype Fix f = Fix { unFix :: f (Fix f) }

instance (Eq (f (Fix f))) => Eq (Fix f) where
  x == y  = unFix x == unFix y
  x /= y  = unFix x /= unFix y

data Foo' a = A
            | B a
            | C a
            | D a a
            | E a a a
            deriving (Eq)

type Foo = Fix Foo'

bar :: Foo -> Foo -> m ()
bar t t' =
  if t == t'
  then undefined
  else undefined
````

**Comment by kandersen** [comment] 2017-01-07 14:47
Also present on 8.0.2 as of today.

**Comment by RyanGlScott** [comment] 2017-01-07 20:20
As noted in https://ghc.haskell.org/trac/ghc/ticket/13081, this is GHC's fault and will be fixed in GHC 8.0.3.

**Comment by wrengr** [comment] 2017-01-08 05:00
Thanks for the notice. Since the bug is actually a regression in `deriving Eq`, presumably users of unification-fd will encounter the same issue in numerous other places as well, so it's not clear that changing the instance will really help very much. I can push out a new version that fixes this particular occurrence of the bug, though it'll affect all 8.0.* versions (meaning adding an unnecessary indirection for >= 8.0.3 due to the effect of NOINLINE).

**Comment by wrengr** [comment] 2017-06-22 05:44
@kandersen I just pushed a version which adds these pragmas. Other GHC-8.0.X versions can just take the performance hit

**Closed** 2017-06-22 05:43 UTC
